#!/bin/bash
echo "Doing autostart on raspi1..."

cd /media/mainusb

screen -X -S Thermoberry quit

screen -d -m -S Thermoberry -s /bin/bash

screen -S Thermoberry -X stuff $'sudo python Thermoberry.py Temperatursteuerung Puffersteuerungraspi1\n'
