sensors:
  sensor_dir: /sys/bus/w1/devices/
  mapping:
    28-0004633651ff: SensorAussentemperatur
    28-00044a21bcff: SensorMischerKeller
    28-0004641778ff: SensorPufferHeizraum1
    28-00044c86b7ff: SensorPufferHeizraum2
    28-0004633961ff: SensorPufferHeizraum3
    28-0004612509ff: SensorPufferHeizraum4
    28-0004633827ff: SensorPufferHeizung1
    28-00046335f6ff: SensorPufferHeizung2
    28-00044e6b6dff: SensorPufferHeizung3
    28-00044c86c8ff: SensorPufferHeizung4
    28-00044e6cc1ff: SensorPufferHygiene1
    28-00044e7371ff: SensorPufferHygiene2
    28-00044e7edbff: SensorPufferHygiene3
    28-00044e75daff: SensorPufferHygiene4


mqtt:
  broker: 192.168.178.40
  port: 1883
  auth: 
    username: 'user2'
    password: 'bar'
