################################################################################
# Node-RED Stack or Compose
################################################################################
# docker stack deploy node-red --compose-file docker-compose-node-red.yml
# docker-compose -f docker-compose-node-red.yml -p myNoderedProject up
################################################################################
version: "3.7"

services:

  # TODO: possible improvements are shown here https://github.com/zinen/docker-alpine-pigpiod/issues/17
  pigpiod: # GPIO daemon https://github.com/zinen/docker-alpine-pigpiod
    image: zinen2/alpine-pigpiod:pigpio-v79
    user: "0:0" # make sure to have root access rights
    restart: unless-stopped # Restarts does happened when binding to GPIOs fails. Auto restarting fixes most problems with hardware access.
    privileged: true
    ports:
      - "8888:8888" # pigpiod daemon access 
    devices:
      - /dev/gpiochip0 # Grant access to GPIO device
      - /dev/gpiochip1 # Grant access to GPIO device
      - /dev/gpiomem # Grant access to GPIO device
      - /dev/mem # Grant access to GPIO device
      # If above device access keeps failing, try setting container to run privileged. 
      # Running privileged is never recommended. But it does fix many problems when access to hardware is required.
    volumes:
      - ./pigpiod/start.sh:/start.sh:r # mount entrypoint
    depends_on:
      - node-red
    entrypoint: /start.sh
    # for pigpiod options see http://abyz.me.uk/rpi/pigpio/pigpiod.html
    #  option -g will run the daemon in the foreground.
    #  option -a 1 should assure that we are not using GPU memory.
    #     for running on 64bit, don't include the '-a 1' flag https://github.com/zinen/docker-alpine-pigpiod/issues/17
    #  option -s 10 reduces sample rate down every 10 micro seconds intead of default 5 https://github.com/joan2937/pigpio/issues/29#issuecomment-151076670
    command: "pigpiod -g -s 10 -n localhost -n 192.168.1.38 -n node-red"

  mqtt: # MQTT Broker
    image: eclipse-mosquitto:2.0.18
    user: "${UID}:${GID}" # make sure the access rights to the files are equal to the hosts user
    restart: unless-stopped # Restarts does happened when binding to GPIOs fails. Auto restarting fixes most problems with hardware access.
    ports:
      - 1884:1883
      - 9002:9001
    volumes:
      - "./mosquitto/config:/mosquitto/config:r"
      - "./mosquitto/data:/mosquitto/data/:rw"
      - "./mosquitto/log:/mosquitto/log/:rw"
  
  node-red: # Node Red https://nodered.org/docs/getting-started/docker
    image: nodered/node-red:3.1.3-18-minimal
    user: "${UID}:${GID}" # make sure the access rights to the files are equal to the hosts user
    restart: unless-stopped # Restarts does happened when binding to GPIOs fails. Auto restarting fixes most problems with hardware access.
    environment:
      - TZ=Europe/Berlin
      - FLOWS=flows.json
    env_file:
      - .env
      - .env.secret
    ports:
      - "1881:1880" # node-red
      # - "1884:1883" # mqtt
    security_opt:
      - seccomp:unconfined # Solution for https://github.com/node-red/node-red-docker/issues/319
    depends_on:
      - mqtt
    privileged: true
    volumes:
      - ./nodered:/data:rw # mount local repository
    entrypoint: /data/entrypoint.sh