################################################################################
# Node-RED Stack or Compose
################################################################################
# docker stack deploy node-red --compose-file docker-compose-node-red.yml
# docker-compose -f docker-compose-node-red.yml -p myNoderedProject up
################################################################################
version: "3.7"

services:

  # GPIO daemon https://github.com/zinen/docker-alpine-pigpiod
  pigpiod:
    image: zinen2/alpine-pigpiod:pigpio-v79
    # privileged: true # save some trouble with accessing GPIOs
    restart: always # Restarts does happened when binding to GPIOs fails. Auto restarting fixes most problems with hardware access.
    devices:
        - /dev/gpiochip0 # Grant access to GPIO device
    # If above device access keeps failing, try setting container to run privileged. 
    # Running privileged is never recommended. But it does fix many problems when access to hardware is required.
    privileged: true
    ports:
      - "8888:8888" # pigpiod daemon access 

  # MQTT Broker
  mqtt:
    image: eclipse-mosquitto:2.0.18
    user: "${UID}:${GID}" # make sure the access rights to the files are equal to the hosts user
    ports:
      - 1884:1883
      - 9002:9001
    volumes:
      - "./mosquitto/config:/mosquitto/config:r"
      - "./mosquitto/data:/mosquitto/data/:rw"
      - "./mosquitto/log:/mosquitto/log/:rw"

  # Node Red https://nodered.org/docs/getting-started/docker
  node-red:
    image: nodered/node-red:3.1.3-18-minimal
    # network_mode: "host"
    user: "${UID}:${GID}" # make sure the access rights to the files are equal to the hosts user
    environment:
      - TZ=Europe/Berlin
      - FLOWS=flows.json
    env_file:
      - .env
      - .env.secret
    ports:
      - "1881:1880" # node-red
      # - "1884:1883" # mqtt
    security_opt:
      - seccomp:unconfined # Solution for https://github.com/node-red/node-red-docker/issues/319
    depends_on:
      - mqtt
      - pigpiod
    privileged: true
    volumes:
      - ./nodered:/data:rw # mount local repository
    entrypoint: /data/entrypoint.sh