logging:
  level: DEBUG
  
sensors:
  sensor_dir: /sys/bus/w1/devices
  mapping:
    28-0004633651ff: sensors/aussentemperatur
    28-00044a21bcff: sensors/heizkreis/vorlauf_ist
    28-0004641778ff: sensors/heizraum/1
    28-00044c86b7ff: sensors/heizraum/2
    28-0004633961ff: sensors/heizraum/3
    28-0004612509ff: sensors/heizraum/4
    28-0004633827ff: sensors/heizkreis/1
    28-00046335f6ff: sensors/heizkreis/2
    28-00044e6b6dff: sensors/heizkreis/3
    28-00044c86c8ff: sensors/heizkreis/4
    28-00044e7edbff: sensors/brauchwasser/1
    28-00044e7371ff: sensors/brauchwasser/2
    28-00044e75daff: sensors/brauchwasser/3
    28-0004633498ff: sensors/brauchwasser/4

heating_circuits:
  - id: steuerung/heizkreis
    topic_requested_temperature: mischer/heizkreis/vorlauf_soll
    topic_enable: steuerung/heizkreis/automatik

    topic_outside_temperature: sensors/aussentemperatur
    topic_supplier_temperature: sensors/heizkreis/1
    topic_supplier_charging: puffer/heizkreis/load
    topic_pump: pumpe/heizkreis/ein
    activation_rules: # bedingungen und abhängigkeiten zum aktivieren der pumpe
      delta_input_over_room_temperature: 4 # °C die das Heizungswasser über der geforderden Raumtemperatur sein muss, damit Heizbetrieb aktiviert wird
      delta_inside_outside: 3 # Mindestunterschied zwischen Raumsoll und Aussen bis Heizung einschaltet
      supplier_temperature_while_charging: 50 # Min Versorgungstemperatur in [°C], während ladevorgang

    room_temperature:
      day: 22
      night: 18
      day_start: "5:30"
      night_start: "22:00"

    requested_temperature_calculation:
      slope: 4.4 # Steigung
      offset: 2 # temperature offset
      max: 60 # Max radiator temperature in [°C]
      fallback: 50 # Backupwert


mixers:
  - id: mischer/heizkreis
    topic_output_actual: sensors/heizkreis/vorlauf_ist
    topic_output_target: mischer/heizkreis/vorlauf_soll
    topic_enable: mischer/heizkreis/automatik
    topic_open: mischer/heizkreis/heiss
    topic_close: mischer/heizkreis/kalt
    cycle_period: 25 # Zykluszeit in [s]
    P: 1 # Fehlergewichtung
    D: 2.8 # Tendenzgewichtung
    temperature_to_time: 3.3 # Umrechnungsfaktor in [s/°C] wandelt temperatur auf zeit um
    hysteresis: 2.0 # Toleranzintervall bzgl. Temperatur für den Mischer

buffers:
  - id: puffer/heizraum
  - id: puffer/heizkreis
    inputs:
      - sensor: sensors/heizraum/1
        loss: 6 #°C
        overheating_sensor: sensors/heizraum/4
        overheating_temperature: 71
    max_temperatures: # disables loading
      "sensors/heizkreis/4": 77
    min_temperatures: # enables loading
      "sensors/heizkreis/1": 40
  - id: puffer/brauchwasser
    inputs:
      - sensor: sensors/heizkreis/1
        loss: 2 #°C
        overheating_sensor: sensors/heizkreis/4
        overheating_temperature: 71
    max_temperatures: # disables loading
      "sensors/brauchwasser/3": 50
    min_temperatures: # enables loading
      "sensors/brauchwasser/1": 55

mqtt:
  broker: "raspi2021-1"
  # broker: 192.168.1.37
  port: 1883
  # auth: 
  #   username: 'user2'
  #   password: 'bar'
